---
- name: Create directories for docker and certbot
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
  loop: ["{{ docker_conf_dir }}", "{{ certbot_webroot }}"]

- name: Check certificate status
  import_role:
    name: certbot_check_only
  when: desired_state == "running"

- name: Copy HTTP-only config to default.conf
  copy:
    remote_src: yes
    src: "{{ nginx_conf_dir }}/prepare/reverse-proxy.conf"
    dest: "{{ nginx_conf_dir }}/default.conf"
  when: 
  - not (cert_valid | default(false) | bool) or not (cert_file_exists | default(false) | bool)
  - desired_state == "running"

- name: Copy HTTPS config with SSL config and redirect
  copy:
    remote_src: yes
    src: "{{ nginx_conf_dir }}/prepare/reverse-proxy-ssl.conf"
    dest: "{{ nginx_conf_dir }}/default.conf"
  when: cert_valid | default(false) | bool

- name: Create docker-compose.yaml
  ansible.builtin.template:
    src: templates/docker-compose.yaml.j2
    dest: "{{ docker_conf_dir }}/docker-compose.yml"

- name: Determine any running services
  ansible.builtin.import_role:
    name: determine_running_services
  vars:
    services:
    - tweet-app
    - nginx

- name: Start services conditionally
  ansible.builtin.set_fact:
    _trigger: true
  notify: "start docker services"
  changed_when: true
  when: 
  - not any_running
  - desired_state == "running"

- name: Recreating services conditionally
  ansible.builtin.set_fact:
    _trigger: true
  notify: "recreate docker services"
  changed_when: true
  when: 
  - any_running
  - desired_state == "running"

- name: Stop services conditionally
  ansible.builtin.set_fact:
    _trigger: true
  notify: "stop docker services"
  changed_when: true
  when: 
  - any_running
  - desired_state == "stopped"

- name: Flush handlers early
  meta: flush_handlers

- name: Issue or renew certificate if required
  import_role:
    name: certbot
  when: desired_state == "running"

- name: Replace HTTP-only config with SSL config
  copy:
    remote_src: yes
    src: "{{ nginx_conf_dir }}/prepare/reverse-proxy-ssl.conf"
    dest: "{{ nginx_conf_dir }}/default.conf"
  when: 
  - not (cert_valid | default(false) | bool)
  - desired_state == "running"

- name: Reload NGINX
  command: docker exec nginx-reverse-proxy nginx -s reload
  when:
  - not (cert_valid | default(false) | bool)
  - desired_state == "running"

