---
- name: Create directories for NGINX and certs
  become: true
  file:
    path: "{{ item }}"
    state: directory
    recurse: true
    owner: admin
  loop: ["{{ nginx_conf_dir }}","{{ nginx_conf_dir }}/prepare"]


- name: Create NGINX reverse proxy config for certbot
  ansible.builtin.template:
    src: templates/reverse-proxy.conf.j2
    dest: "{{ nginx_conf_dir }}/prepare/reverse-proxy.conf"

- name: Create NGINX reverse proxy config with redirect
  ansible.builtin.template:
    src: templates/reverse-proxy-ssl.conf.j2
    dest: "{{ nginx_conf_dir }}/prepare/reverse-proxy-ssl.conf"
